### ISSUE TITLE
What do I do with this version?

### ISSUE THREAD

**Issue by MrAda** [cnlohr/esp_nonos_sdk#1]
I took your suggestion and try to use this branch and I don't know how to proceed with it.  I tried doing make and it choked:

make[1]: Entering directory '/home/chris/Desktop/esp_nonos_sdk-master/driver_lib'
make[2]: Entering directory '/home/chris/Desktop/esp_nonos_sdk-master/driver_lib'
make[2]: *** user: No such file or directory.  Stop.
make[2]: Leaving directory '/home/chris/Desktop/esp_nonos_sdk-master/driver_lib'
../Makefile:309: recipe for target '.subdirs' failed
make[1]: *** [.subdirs] Error 2
make[1]: Leaving directory '/home/chris/Desktop/esp_nonos_sdk-master/driver_lib'
Makefile:309: recipe for target '.subdirs' failed
make: *** [.subdirs] Error 2

**Comment by cnlohr** [comment]
I'm not sure what you are doing specifically.  The SDK does not need to be built.  It is just a collection of .a and .h files that a separate project will link to.  What project do you intend to build against it?

**Comment by MrAda** [comment]
I was going to try and use it for my GPIO/Ethernet related project I am working on.  I guess I don't know how to use this off the top of my head.  It is so frustrating working with the NODEMCU.  There are splatterings of help on the net and right now I am focused on trying to get the GPIO stuff to work.  But from what I can tell I have to tell the "system" which pin is what and the  NODEMCU seems to scramble things around.  So I am trying to avoid 16! combinations to find the right configuration.

**Comment by cnlohr** [comment]
/maybe/ ESP82xx would be best for you.  This project here is specifically for people who know they want to use the regular ESP8266 NONOS SDK but need more resources than it normally allows.

**Comment by brainstorm** [comment]
@MrAda, if you want to use this, you should just tweak the `SDK` variable in `user.cfg`:

```
SDK_DEFAULT  = $(HOME)/esp8266/esp-open-sdk
SDK = $(HOME)/esp8266/esp_nonos_sdk
ESP_GCC_VERS = 4.8.5
```

Assuming that you are using [esp82xx-basic](https://github.com/con-f-use/esp82XX-basic) as @cnlohr points out.

**Comment by MrAda** [comment]
thanks for the help.  I don't mind using the esp82xx-basic if I can do ethernet/wifi and gpio related stuff.

**Comment by MrAda** [comment]
esp82xx-basic seems to have broken links.  seems a lot of items are pointing to esp82xx folder and nothing exists there

**Comment by MrAda** [comment]
I got my arduino version of my GPIO and UDP program working. I can now control my relays over the net.

**Comment by cnlohr** [comment]
As long as it works!

Re: esp82xx, you have to do a recursive git pull to make it check out all the submodules.
